#!/usr/bin/env bash

trap 'rm -rf $tmp_dir' EXIT

dir=""
tmp_dir=$dir/autograder/tmp
test_dir=$dir/autograder/source/tests
sub_dir=$dir/autograder/submission

rm -rf $tmp_dir
mkdir -p $tmp_dir

tmp_err=$tmp_dir/err.txt
tmp_sub=$tmp_dir/submission.pie
tmp_res=$tmp_dir/results.json

results=$dir/autograder/results/results.json
rm -f $results

write () {
    echo -n $1 >> $tmp_res
}

write_file () {
    cat $1 >> $tmp_res
}

run_test () {
    cp $1 $tmp_sub
    echo -e "\n\n\n" >> $tmp_sub
    cat $2 >> $tmp_sub
    racket $tmp_sub 2> $tmp_err
}

write "{\"score\":0.0,\"tests\":["
submitted=0
shopt -s nullglob
for f in $sub_dir/*.pie
do
    if [ $submitted -eq 0 ]
    then
        submitted=1
        run_test $f ""
        if [[ "$(cat $tmp_err)" == "" ]]
        then
            write "{\"score\":1.0,\"max_score\":1.0,\"name\":\"Runs\"}"
            for t in $test_dir/*
            do
                write ",{\"name\":\"$(basename $t)\",\"visibility\":\"hidden\",\"output\":\""
                write "====\nTEST\n====\n\n"
                write_file $t
                run_test $f $t
                if [[ "$(cat $tmp_err)" == "" ]]
                then
                    write "\n\n======\nPASSED\n======"
                else
                    write "\n\n==========\nNOT PASSED\n==========\n\n"
                    write_file $tmp_err
                fi
                write "\"}"
            done
        else
            write "{\"score\":0.0,\"max_score\":1.0,\"name\":\"Runs\",\"output\":\""
            write "======\nOUTPUT\n======\n\n"
            write_file $tmp_err
            write "\"}"
        fi
    fi
done
if [ $submitted -eq 0 ]
then
    write "{\"score\":0.0,\"max_score\":1.0,\"name\":\"Runs\",\"output\":\"NO SUBMISSION FOUND\"}"
fi
write "]}"

sed '$!s/$/\\n/' $tmp_res | tr -d '\n' > $results
